USE master;
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'ZyDBBak20200408';
go
 
CREATE CERTIFICATE AutoBakCert FROM FILE = N'{0}\AutoBakCert.cer'
WITH PRIVATE KEY (  FILE = N'{0}\AutoBakCert.pkey', DECRYPTION  BY PASSWORD ='Cert123');
IF @@ERROR <>0
	PRINT N'启用证书和主控密钥失败！！！！';
ELSE
   PRINT N'启用证书和主控密钥完成';
GO